version: '3.8'

services:
  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_DB: shortify
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 8011:5432
  flask:
    container_name: flask
    build:
      context: app
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    tty: true
